version: "3"
 
services:
  sonarqube:
    image: sonarqube:8.7.1-community
    container_name: sonarqube
    restart: always
    environment:
      - SONARQUBE_JDBC_USERNAME=chronos
      - SONARQUBE_JDBC_PASSWORD=I%1AVkw9XA5xxqkEu94RM%iSCdFCChfQ
      - SONARQUBE_JDBC_URL=jdbc:postgresql://postgresql-24510-0.cloudclusters.net:24510/chronos-sonar
    ports:
      - "9000:9000"
      - "9092:9092"
    volumes:
      - sonarqube_conf:/opt/sonarqube/conf
      - sonarqube_data:/opt/sonarqube/data
      - sonarqube_extensions:/opt/sonarqube/extensions
      - sonarqube_bundled-plugins:/opt/sonarqube/lib/bundled-plugins
volumes:
  postgresql_data:
  sonarqube_bundled-plugins:
  sonarqube_conf:
  sonarqube_data:
  sonarqube_db:
  sonarqube_extensions:
